[workspace]
resolver = "2"
members = [
    "app",
    "crates/raikou",
    "crates/raikou-core",
    "crates/raikou-style",
    "crates/raikou-widgets",
    "crates/raikou-playground",
    "crates/raikou-demo",
    "examples/button_demo",
    "examples/widgets_demo",
    "examples/forms_demo",
    "examples/containers_demo",
    "examples/menu_demo",
    "examples/context_menu_demo",
    "examples/select_demo",
    "examples/combobox_demo",
    "examples/tree_demo",
    "examples/table_demo",
    "examples/loading_demo",
    "examples/playground_demo",
    "examples/combobox_playground",
    "examples/context_menu_playground",
    "examples/label_playground",
    "examples/loading_indicator_playground",
    "examples/menu_playground",
    "examples/progress_bar_playground",
    "examples/radio_playground",
    "examples/scroll_area_playground",
    "examples/step_input_playground",
    "examples/switch_playground",
    "examples/table_playground",
    "examples/tabs_playground",
    "examples/text_area_playground",
    "examples/text_input_playground",
    "examples/tree_playground",
    "examples/popover_playground",
    "examples/button_playground",
    "examples/checkbox_playground",
    "examples/select_playground",
    "examples/accordion_playground",
    "examples/image_playground",
]
default-members = ["app"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.94"

[workspace.dependencies]
fyrox = { git = "https://github.com/FyroxEngine/Fyrox", rev = "d30f42867f526a07608a56975e1c128872b17d33" }
smol_str = "0.2.2"
uuid = "1"
raikou = { path = "crates/raikou", version = "0.1.0" }
raikou-core = { path = "crates/raikou-core", version = "0.1.0" }
raikou-style = { path = "crates/raikou-style", version = "0.1.0" }
raikou-widgets = { path = "crates/raikou-widgets", version = "0.1.0" }
raikou-demo = { path = "crates/raikou-demo", version = "0.1.0" }
raikou-playground = { path = "crates/raikou-playground", version = "0.1.0" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
